FROM php:7.4-fpm

# Use https://github.com/mlocati/docker-php-extension-installer to easily install PHP extensions
# ctype curl iconv dom json mbstring openssl pcre PDO Reflection spl xml are required by Craft but installed by default
# intl is recommended, ImageMagick is recommended over GD
RUN curl -sSLf \
        -o /usr/local/bin/install-php-extensions \
        https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions imagick intl opcache pdo_mysql zip @composer-1 && \
    mkdir -p /var/www/html

# We do not run composer install since it needs to be run once the volume is mounted

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Install node using https://github.com/nodesource/distributions
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs

# We do not run npm install since it needs to be run once the volume is mounted
RUN npm install gulp-cli -g

COPY files/entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "entrypoint.sh" ]