version: '2.4'
services:
    esk8:
        build:
            context: .
        container_name: esk8
        ports:
            - 9008:9000
        volumes:
            #TODO: mount volume for uploads
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: unless-stopped